name: Publish in npm
on:
  push:
    branches: Livraison

jobs:
  job_publish:
    name: Publish if merged
    runs-on: windows-latest
    steps:
      - run: echo merged and ready to publish
      - uses: actions/checkout@v3
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@master
        with:
          node-version: 21
      - name: Install dependencies
        run: npm install
#              npm install --save-dev electron-builder-squirrel-windows@25.1.8
      - name: Build
        run: npm run make
 #       run: | 
#              echo ${{ secrets.NPM_TOKEN }}
#              echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > .npmrc
#              npm publish --access public --ignore-scripts
#        env:
#          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
